<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shashwat" failures="1" tests="1" name="Test2" time="14.699" errors="0" timestamp="21 Sep 2018 11:08:25 GMT">
  <testcase classname="yahooTestCases.SignUpTestCases" name="SignUpToYahoo" time="3.14">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at yahooTestCases.SignUpTestCases.SignUpToYahoo(SignUpTestCases.java:23)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- SignUpToYahoo -->
</testsuite> <!-- Test2 -->
